### PR TITLE
small cleanup

### PR DESCRIPTION
**Pull request by bekzod**
* replaced `Ember.$` => `$`;
* moved `getElementPosition` out of class it is more like utility function and not relate to class so I think it is better stay outside of the class;
* removed `ember-cli-ic-ajax` as it is not being used and won't be used I think 
* `Ember.A()` don't need initial value I 

everything mixed up in one commit :smile:

### CODE REVIEW

**Comment by rwwagner90** [comment]
@bekzod everything looks good in this cleanup, one small suggestion though, if we are taking `getElementPosition` out of the class, could we make a utils.js or something and import that then call `Utils.getElementPosition`? Just an idea, and that way we would have a place set up to put utils in the future, if they are needed.

**Comment by rwwagner90** [comment]
Going to merge this, might revisit the utils stuff later, but this is mostly good.

**Comment by bekzod** [comment]
cool thanks, forgot to comment on this, I agree on that point

**Comment by rwwagner90** [comment]
@bekzod not sure what the deal is, but the build is failing now.

**Comment by bekzod** [comment]
having a look

**Comment by rwwagner90** [comment]
https://travis-ci.org/rwwagner90/ember-shepherd/jobs/95136688

**Comment by bekzod** [comment]
locally all tests pass no idea why it is failing

**Comment by rwwagner90** [comment]
@bekzod I posted the output from the build above. Please check out https://travis-ci.org/rwwagner90/ember-shepherd/jobs/95136688

**Comment by bekzod** [comment]
can you restart it, if it keeps on failing, I guess you can revert the merge

**Comment by bekzod** [comment]
found out it fails `ember try:test all` wasn't clear from travis output
ember-beta: FAIL
ember-canary: FAIL

**Comment by bekzod** [comment]
but even master before merge fails those :)

**Comment by rwwagner90** [comment]
Hmm, not sure why it's failing that stuff. @alexlafroscia was the ember try stuff passing before?

**Comment by rwwagner90** [comment]
@bekzod @alexlafroscia I think we just have some deprecations, going to attempt to fix them

**Pull request merged**
