### PR TITLE
Allow action to be passed to builtin buttons options and make buttons to be created even if their type is not one of (next,exit,back)

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by rwwagner90** [comment]
Hi @bekzod thanks for the PR! Would you mind writing some tests for your code please? The code looks fine, but I would prefer that all PRs have accompanying tests written.

**Comment by bekzod** [comment]
will do

**Comment by rwwagner90** [comment]
Thanks for understanding @bekzod! Out of curiosity, how do you like Ember-Shepherd?

**Comment by bekzod** [comment]
compared to other touring libraries I think it is simplest and easiest to use, code could be changed here and there to make it better and solid, but overall good library :+1:

**Comment by rwwagner90** [comment]
@bekzod glad you like it. Would you be interested in being made a collaborator on the repo? We're always looking for good people to help make Ember-Shepherd better. 

Thanks for writing those tests too, I will merge now.

**Comment by bekzod** [comment]
@rwwagner90 yes, sounds awesome thanks

**Comment by rwwagner90** [comment]
@bekzod added you as a collaborator on GitHub and contributor on npm. Please let me know ideas you have for making the library better and feel free to throw some PRs up :smile:

**Comment by bekzod** [comment]
@rwwagner90 great thanks, had issue that I want to solve if possible make tour step element to dynamically/lazily searched in usage time not in setup time, so elements might not exist in beginning but   can appear later (like once models loaded)

**Comment by bekzod** [comment]
and I was thinking changing api too instead of `.trigger('cancel');` => .`cancel` simple function, `.trigger('cancel')` looks like tampering with internals  ?

**Comment by rwwagner90** [comment]
@bekzod I'm not sure if it's possible with [Shepherd](https://github.com/HubSpot/shepherd) to do lazily loaded elements, but what you may be looking for is `beforeShowPromise` which is part of the core Shepherd library. I added that to be able to do logic before the `show` function is called for the step.

As for simplifying, go for it :smile:

**Pull request merged**
