### PR TITLE
initial commit - ember-onboarding files

### PR DESCRIPTION
**Pull request by thiagoc7**
Let's try to build a complete tour system for Ember!

I added my files in this PR, so we have all here, but it's not supposed to be merged.

I created another `shepherd` addon because I need my code to be very organised, or I get lost.

So, my suggestion as our first task would be defining the `UX` of the addon.
By `UX` I mean how we want our users to install and interact with the library.

For this kind of addon, that is not in the heart of any application, I think that it's better to keep all the code in one place. It can be one file, one folder, etc, but must be separated from the main project files.

For my experience with `Ember` (that is not very extensive), we can use two entities for that:
- Components
- Services

What do you think?

### CODE REVIEW

**Comment by rwwagner90** [comment]
So you think we should tie it into the app for them? Just inject it into the application as a service, and then override the steps in the service and such from routes?

My setup currently is just one component and you pass all the steps and such into it, but we could start by injecting the steps into the component as a service, instead of having the user define them directly and passing them in.

Sound like a logical first step?

**Comment by rwwagner90** [comment]
@thiagoc7 I'll start working on a service for the steps, if you agree that's a good place to start.

**Comment by thiagoc7** [comment]
Hi @rwwagner90!
I just think we should find a way to build the addon in an unobtrusive way.
I was researching about it, and liked the way [i18n](https://github.com/dockyard/ember-cli-i18n) solved this problem.
You create the translations inside `locales` folder, and it does not mess with your main code.

We could inject the steps like you said, but don´t you think that if we use `dockyard`'s approach we would have more flexibility?

Cheers!

**Comment by thiagoc7** [comment]
something like:

```
app
└── tours
    └── tour1.js
    └── tour2.js
```

Then export a single POJO:

```javascript
//app/tours/tour1.js

export default {
  steps: {
    title: 'Welcome'
  }
};
```

**Comment by alexlafroscia** [comment]
@thiagoc7 I think the idea of having the tour steps outside of the controllers is a nice feature; it's sort of messy to have a gigantic JSON configuration object inside each controller that has a tour on it.

I think a nice step would be having a mixin that applied some functionality to the controllers that have a tour.  For instance, I created a mixin to use with `ember-shepherd` that adds the `showHelp` property and an action to set it, and so far it's nicer than putting all of that configuration inside each controller.

**Comment by rwwagner90** [comment]
We can have people define the steps in self contained files, that just makes it a bit messy to get all the contexts passed back and forth.

@alexlafroscia so it sounds like you're thinking define each tour in a separate file, then pull them all into a service automatically and namespace them somehow, then look them up by name in the component?

As for a mixin, I'm all for that, I just don't want to obfuscate what is available. I want everyone to know what's going on. We need to structure everything around the new ideals of not using components, so services, components, and routes.

Where should we get started?

**Comment by alexlafroscia** [comment]
@rwwagner90 yeah, that sounds about right (we do something similar to that to look up custom files in our app right now and it works well).  I think a mixin would be nice for providing basic configuration, since a controller could always overwrite the default behavior.  We could even have the mixin set up that it gives a warning in the console if the mixin is included but steps for that controller haven't been defined...

I think a nice setup might be something like this: a controller imports and includes a mixin that says that there should be a tour on that page.  The mixin provides some default configuration, and determines that a `steps` property _must_ be defined (sort of like an interface).  Then, a user can either define the steps in that file, or decide to import it from another file.  As an addon, maybe this shouldn't require the use of external files at all.

I'm not that familiar with Shepherd; what information would need to be shared between components, that a service would provide?

**Comment by rwwagner90** [comment]
@alexlafroscia I agree with the idea behind what you're saying, but we can't use controllers, since they'll be gone in Ember 2.0. We can have a mixin that you can include in your routes, when you want a tour for that route. I'm not sure how helpful it'll be though because the user would just need to override any defaults, at that point, if they didn't like them. I'll start working on a common mixin of some sort though.

My thought with the service was, you can just have the one ember-shepherd component, and inject the service into it, then you can just set steps and such on the service, and they would be injected into the component, instead of needing to pass them in explicitly.

**Comment by rwwagner90** [comment]
@thiagoc7 we've gone quite a different direction, and started using a service and no component. Feel free to take a look and offer suggestions, but going to close this.

**Pull request closed without merging**
