### PR TITLE
Remove initializer deprecations

### PR DESCRIPTION
**Pull request by alexlafroscia**
- Do some lookups from an instance initializer to avoid deprecation warnings
- Updated dependencies
- Updated some font-related CSS that caused issues with rendering the dummy site

### CODE REVIEW

**Comment by rwwagner90** [comment]
@alexlafroscia the changes look good to me, but travis seems to be throwing errors. Do the tests all pass?

**Comment by alexlafroscia** [comment]
Huh, not sure what the problem is. I updated the plugin to use `ember-try` and it seems like something might have gone wrong in there. I'll check it out.

**Comment by rwwagner90** [comment]
:+1:

**Comment by rwwagner90** [comment]
Any progress on the fixing the tests front? I can take a look, but won't have time until a couple days from now.

**Comment by alexlafroscia** [comment]
I haven't tried yet, I've been busy with work and other open-source stuff.  I'll try to take a crack at it tonight.

**Comment by rwwagner90** [comment]
No worries. Just checking in. Keep me posted

**Comment by alexlafroscia** [comment]
Alright, so I looked into the issue and was able to get the tests running, at least. I think something was up with the `ember-cli-blanket` package, so I just removed it.

Now I'm working on getting the tests working through `ember try`, which will test against the current, beta and canary version of Ember. One thing that I did some across when reviewing the failing tests is that there really isn't a strategy for testing instance initializers yet; there's still no blueprint for them in the Ember CLI and I'm not exactly sure how you would write a test setup for them manually. For the time being, I just disabled that test so I can focus on fixing everything else.

**Comment by rwwagner90** [comment]
@alexlafroscia that sounds fine. Just need the tests to be passing before we can merge. We can wait until testing methods for instance initializers solidify or I can ask around on slack and see if we can figure it out.

**Comment by alexlafroscia** [comment]
Yeah, let's just ask around. I'll finish this up tonight.

**Comment by alexlafroscia** [comment]
Alright, this is good to go :+1:

**Comment by alexlafroscia** [comment]
Any idea why the "push" and "pr" hooks are both being run?

**Comment by rwwagner90** [comment]
@alexlafroscia not sure why both are being run, I will take a look. Thanks for fixing all this!

**Comment by alexlafroscia** [comment]
Sure thing! And that actually might just be the way that Travis does it, I've seen that on other repos, like [this](https://github.com/alexlafroscia/vim-ember-cli/pull/2).  Probably not something we can fix, and if they choose to run the tests twice for no reason, that's up to them.

**Comment by rwwagner90** [comment]
@alexlafroscia what else do you think we need to do to make this 1.0? I'm thinking we just wait for an Ember 2.0 release and fix any deprecations we may have.

**Comment by alexlafroscia** [comment]
Do we have any deprecations now? If we don't now, I don't think we will after 2.0 is released...

If you're happy with this, I think this is probably 1.0-ready

**Comment by rwwagner90** [comment]
I'm pretty happy with it. I'll take one last look at the code and the README and we can go ahead and release 1.0

**Comment by alexlafroscia** [comment]
:+1:

**Pull request merged**
