### PR TITLE
Support attachto object

### LINKED ISSUE #6: Doesn't support attachTo object
Shepherd seems to allow you to use an object to define the `attachTo` behavior:

> For example: ".some #element left", or {element: '.some #element', on: 'left'}. If you use the object syntax, element can also be a DOM element. If you don't specify an attachTo the element will appear in the middle of the screen.

However, trying to use this with `ember-shepherd` breaks the tour with the following error

> Uncaught TypeError: currentStep.options.attachTo.split is not a function

Which corresponds to the [code found here](https://github.com/rwwagner90/ember-shepherd/blob/master/addon/components/ember-shepherd.js#L30).

### PR DESCRIPTION
**Pull request by alexlafroscia**
There's a bit of cleanup and refactoring that I did while adding this feature.  I added tests for my new additions, too.

Closes #6

### CODE REVIEW

**Comment by rwwagner90** [comment]
@alexlafroscia it mostly looks good, but I would also support passing the DOM element itself perhaps, since Shepherd supports that. That way, we would be fully compatible. What are your thoughts on that?

Travis CI doesn't seem to be happy for some reason. It builds, but then never runs the tests or anything.

Thanks so much for undertaking this!

**Comment by rwwagner90** [comment]
@alexlafroscia determined the issue. ES6 is not supported, in the addon directory, for whatever reason. So you'll need to change your const back to plain vars. This allows PhantomJS to run it, and should fix the Travis CI issues.

**Comment by rwwagner90** [comment]
Just kidding, putting babel in the dependencies fixes it.

**Comment by rwwagner90** [comment]
Going to go ahead and merge, as this appears to work, once babel is added to deps.

**Comment by rwwagner90** [comment]
@alexlafroscia solid work. The only remaining thing to discuss, would be supporting passing DOM elements as well. Thoughts?

**Comment by alexlafroscia** [comment]
That should just work out-of-the-box.  If it detects that `attachTo` is an object, it just passes the element value into `$( )`.  Whether it's a string, jQuery element or vanilla JS DOM element, it should create the same thing.

**Comment by rwwagner90** [comment]
It looks like it only supports object syntax, not a DOM element, to me.
https://github.com/rwwagner90/ember-shepherd/blob/master/addon/components/ember-shepherd.js#L232-242

Where is the case of the element being passed in handled? It's possible you're handling it and I just missed it, but the switch appears to do string or default case, and default just assumes it's an object, not a DOM element.

**Comment by alexlafroscia** [comment]
Oh sorry, you want to allow `attachTo` to be a DOM element itself?  I thought you meant that `attachTo.element` should be able to be a DOM element.  I didn't add the former case, although I can do that if you want.  How would people specify `top/bottom/left/right` then?

**Comment by rwwagner90** [comment]
Hmm, I didn't think about that. I suppose they couldn't specify a position then. Let's just leave it as is then. Nice work on this. I'm looking for collaborators to help out on a more permanent basis with getting this up to a polished release for the community. Would you be interested?

**Comment by alexlafroscia** [comment]
Yeah, totally. We're using this for a project at work now, so I'm definitely interested in making it as nice as possible :) Are there any things in particular that are on your to-do list or that you want refactored?  If you make issues for stuff that's on your horizon, I can take a look at them and see what I can take on.

**Comment by rwwagner90** [comment]
I don't have anything in particular in mind. I did want to try to incorporate any of the changes that made sense to use from ember-onboarding and I would like to break some stuff out into services, like steps. My only stipulation is we should try to gear everything toward Ember 2.0, so no using views or controllers. Other than that, I'm open to any ideas that would help make the library nicer for your use case or for the community in general. I'll put up a couple issues this weekend or early next week. Anything that you think would be nice to have, feel free to throw an issue up as well. We can create a backlog sort of and discuss how we want to do each feature. Sound good?

**Comment by alexlafroscia** [comment]
:+1:

**Pull request merged**
