### PR TITLE
Remove shepherd component

### PR DESCRIPTION
**Pull request by alexlafroscia**
Switch from component to service.

### CODE REVIEW

**Comment by rwwagner90** [comment]
Why did you remove the injection into all routes and controllers? I thought that was nice.

**Comment by rwwagner90** [comment]
@alexlafroscia I made some edits.

Most of them were just alphabetizing things, tweaks to the text in the tour, and little stuff like that.

The one thing I did do though, was I added back the auto injection, as I think that's nice. It makes the addon usable immediately after install from any route or controller, and doesn't require the user to manually inject it. Perhaps that's bad form, but I think it's nifty. Thoughts?

One more picky thing, that I'm not sure how stringent you are on, but would you mind if we removed the _ from private methods? I'm not a fan of that. I know it's something a lot of people do, but I'd prefer to remove it, if don't have your heart set on keeping them. I've marked each with `@private` to indicate they are private.

Overall, really great work. I think this is about ready to merge. I might want to take another more in depth look at some point, but I have a deadline at work coming up, and I really have to devote my time to that this week, so I can't do much now. 

Thanks for putting in the work on this! :+1:

**Comment by alexlafroscia** [comment]
No worries, I'm in no rush to pull this. We're trying to use it at work right now, and just pulled it in from the branch.  I'm having some trouble getting it to attach an element to an item that's hidden at the point that the tour starts -- any ideas on what the best way to approach that might be?

**Comment by alexlafroscia** [comment]
> Why did you remove the injection into all routes and controllers? I thought that was nice.

I made a note about it in the commit that contains that change.  I try to do that whenever I do something that might warrant an explanation.

> Using Ember.inject.service is what's suggested, so I think it makes more sense to just stick with that.  Also, for some reason by injecting the ApplicationController into the tour service in the initializer (so we can reference the currentRoute property), the ApplicationController wasn't able to use `this.tour` to reference the tour, despite the `Ember.inject`-based API working fine.

It seemed like something with that circular dependency was off when using the injection API, but `Ember.inject` was fine

**Comment by rwwagner90** [comment]
@alexlafroscia attaching to elements that are hidden or do not exist when the tour starts can be achieved using `beforeShowPromise`. You'll want to do whatever you need to do to get the elements showing there, and then attachTo will work. It will not work if you don't use Shepherd's attachTo though and try to use the jquery selector stuff. Can you apply classes or ids or some sort of selector that is supported in CSS and not jquery specific?

Ah, I didn't actually read the commits, just looked at the code as a whole.

I switched it back to using the auto injection in the initializer, and all the tests passed and everything. Can you confirm if anything is broken? You mentioned the ApplicationController could not use this.tour, but it appears the route can. Just curious if that's still an issue?

**Comment by alexlafroscia** [comment]
Huh, it's weird that it works for you now, but if it does, great.  I was seeing problems, but I don't remember specifically what it was.

**Comment by rwwagner90** [comment]
Could be it works with routes and not controllers? Not sure why it would, but if you find no issues with it, I'd like to leave it for now. It's easy enough to put it back to manual injection later, if we need to.

How do you feel about removing _ from private methods?

**Comment by alexlafroscia** [comment]
If you take a look at the [jit-step-addition](https://github.com/rwwagner90/ember-shepherd/tree/jit-step-addition) branch I've been playing with, I actually moved a lot of the private methods out of the service entirely since they were pure functions, for the most part.  That cleaned up a lot of the private methods.

**Comment by alexlafroscia** [comment]
> It's easy enough to put it back to manual injection later, if we need to.

For sure. The manual injection works either way, and I like the fact that it's a little more explicit about where the `tour` actually comes from, but if it works for you I'm fine with leaving it in place.

**Comment by rwwagner90** [comment]
The underscore thing is entirely personal preference. I'm fine with moving functions out of the service. Can we put them in some kind of util file or something? Rather than leaving them in the service file?

**Comment by alexlafroscia** [comment]
Yeah, we can do a util file instead.  That branch is a major WIP since it changes how it works under the hood quite a bit.  Finding the element as the step is triggered fixed the issue though, and I think is a better approach than using that promise hook

**Comment by rwwagner90** [comment]
@alexlafroscia are you referring to your previous idea of adding the step to the tour on 'next'? We're getting into replacing Shepherd and not being a wrapper for it, if we start down that road, are we not? 

We could maybe one day just write an entire tour plugin ourselves, but if we hijack Shepherd and stop it from doing its normal behavior, I think that's working against what we should be doing. `beforeShowPromise` will work, with the correct implementation. You could write something on our end that wraps beforeShowPromise, if you would like, but lets let Shepherd do its job.

This is assuming that I understood you correctly, but I may have no idea what I'm talking about :stuck_out_tongue:

**Comment by alexlafroscia** [comment]
Yeah, that's what I'm talking about.  I know it's hacking Shepherd and I know that you're not into that -- that's why I started a new branch to try that and am honestly not planning on submitting that as a PR at all.  However, hacky or not, it got what I've been struggling with for the last few days to work and allowed me to progress, so I think it was worth doing.

> We could maybe one day just write an entire tour plugin ourselves

I've been thinking about this lately; there seems to only be one "native" Ember tour project, and it hasn't been updated in ~3 months, and there's little documentation on it.  I think it would be interesting to take what we've been figuring out here (for example, using only a service, which IMO is a much better idea than using components) and trying to make something from scratch that can handle many of the use cases that are common in Ember but maybe not so common in static-page-focused apps.

**Comment by rwwagner90** [comment]
I agree with all of that. I think we should knock out everything with Ember-Shepherd and get it solid and full of the features we want to see, release 1.0, and then we can start on a separate tour library and try our hand at that. How does that sound?

**Comment by alexlafroscia** [comment]
:+1:

**Comment by rwwagner90** [comment]
Not too much. I'd say we could go ahead and merge this, then see if we encounter anything else we might want to fix or features we may want to add over the next couple weeks. I'll be able to do more after my deadline at work.

**Comment by rwwagner90** [comment]
If you're happy with this, I say we merge it and mark it as 0.5, then we can push anything else toward 1.0 after that. Thoughts?

**Comment by alexlafroscia** [comment]
Probably makes sense.

**Pull request merged**
