### PR TITLE
Convert from Component to Service

### PR DESCRIPTION
**Pull request by alexlafroscia**

### CODE REVIEW

**Comment by alexlafroscia** [comment]
This should be mostly good; all of your tests have been modified to pass with the new flow (and they only needed to change at app because they were manipulating the controller that the component was getting properties from.

What's still left for me to do it fixing the tests that I added in 3cd5459, since I don't know how to have the Service unit test check for an element against the DOM.  Maybe the actual DOM search can be pulled into a separate method and stubbed?  We could also write an integration test, but this seems like something that should be covered by a unit test.

**Comment by rwwagner90** [comment]
In my opinion, integration tests are more important, since we're relying on a lot of non-Ember stuff here. I'm okay with not having unit tests, but would like to cover as many cases as we can with integration tests. That sound okay with you?

**Comment by alexlafroscia** [comment]
Yeah, sure thing.  I'll go back and add integration tests to cover those cases and update this PR.

**Comment by rwwagner90** [comment]
Sounds good man. I'm inclined to go ahead and merge this, once you update those integration tests, then I'll make another branch and update a couple things myself. Does that make sense or do you think we should try to confine it all to this PR?

**Comment by alexlafroscia** [comment]
Maybe it's better to confine it to this PR? Might be cleaner.

**Comment by rwwagner90** [comment]
I'll work off of this PR then. I didn't get a chance to do anything last night. I'm juggling a lot right now, but we should be able to get this buttoned up this week for sure.

**Comment by alexlafroscia** [comment]
This no longer works with Ember 1.12.0 and the move to "instance initializers".  I tried installing this branch into an Ember 1.12 app and it just breaks.  I'll update the PR to use the correct type of initializer.

**Comment by rwwagner90** [comment]
@alexlafroscia awesome, appreciate it. I've been insanely busy this week. I haven't forgotten about this PR. I'll make my tweaks and merge it by Sunday at the absolute latest.

**Comment by alexlafroscia** [comment]
Cool. I've been busy too :)

**Comment by alexlafroscia** [comment]
Alright, I added a few things:

- Use any jQuery selector string with the `attachTo` object.  This allows pseudoselectors to work, which is a feature that I really needed but isn't supported by Shepherd out-of-the-box.  We get around that by taking the string that is passed to the `attachTo` configuration, finding the element using jQuery, and then passing the "raw" DOM element to Shepherd.  Previously, we would use jQuery for our own internal element locating, but still passed Shepherd a string.
- Adds tests to verify that finding an object with an "advanced" selector (`:first` for example) works correctly.

**Comment by alexlafroscia** [comment]
One thing I'm not sure of it whether killing the tour when the route changes works (I don't think there's a test for it yet).  I'm also not 100% sure we actually want that as a feature, too.  It might make more sense to allow people to handle killing it on page change if they want to instead of forcing that feature, right?

**Comment by rwwagner90** [comment]
Selectors :+1: 

Route change, I'm not so sure. We can't really allow the tour to still be open because the DOM elements will get blown away on route change and mess up the tour.

**Comment by alexlafroscia** [comment]
Yeah, that's true. I already have it set up so that the tour service has the Application Controller injected into it, and from there created a computed property on the service for the current route.  My hesitation is that using `.observes

**Comment by rwwagner90** [comment]
You're injecting the controller just to get currentRoute? I think we should probably approach that another way.

**Comment by alexlafroscia** [comment]
How can we, though? `currentRoute` doesn't exist as a property of anything other than the application controller, and I don't think there's any problem with it.  Here's the [injection](https://github.com/alexlafroscia/ember-shepherd/blob/remove-shepherd-component/addon/initializers/tour.js#L4-L6) and here's the [computed property](https://github.com/alexlafroscia/ember-shepherd/blob/remove-shepherd-component/addon/services/tour.js#L5-L7).

**Comment by rwwagner90** [comment]
Yeah, I suppose you're right. It just feels weird to me to inject an entire controller for one thing, but there may be no way around it.

**Comment by alexlafroscia** [comment]
I agree, but it's really not _that_ different than passing `currentPath` as a property, the way that component used to handle it.  The difference is that a user of the library doesn't have to think about it at all anymore.

Maybe we could try to make it easier and create the `currentPath` property directly from the initializer?  The problem I see is that I don't think that `currentPath` would stay in sync with the application controller's property if it was done like this:

```javascript
const service = container.lookup('service:tour');
const appController = container.lookup('controller:application');
service.set('currentPath', appController.get('currentPath'));
```

Another concern that I have is that the initializer should, I think, but an "instance initializer", but that's only supported in Ember 1.12+.  Can we support different files for different versions?

**Comment by rwwagner90** [comment]
I see no reason not to only support the latest Ember. We're already breaking how it used to work anyway. We could make a legacy branch that points to the code before we started on the service, for anyone that may need the old stuff.

**Comment by rwwagner90** [comment]
Also, I tried to add to your PR, but it appears that I ended up just pushing a new branch instead. Oops. How am I supposed to add to here?

**Comment by rwwagner90** [comment]
I think we need to just create multiple PRs. We should merge this into the tourService branch and subsequently merge everything into that branch until we're happy with it, then merge that to master. That work for you? We can keep PRs smaller and more manageable as well.

**Comment by alexlafroscia** [comment]
To update the PR directly, you would push to my branch.  I would recommend that you submit a PR to me against this branch; we can go over the changes there, and when I pull that into my branch, it'll update this PR with your new changes.  That's how we handle these situations at work, anyway.

***

I'm currenly dogfooding this PR in my add for work, and one thing I noticed with the changes to using the jQuery selectors is that they would be more useful if they were lazily evaluated.  For example, I am trying to attach a step to an element that is hidden in the DOM at the time that the tour starts, but eventually is shown as part of the tour (it's part of a drop-down menu).  Because all of those jQuery selections are done up-front, the element is `undefined` initially.

What do you think about changing it to add the step to the tour as the "next" step is triggered?  It would mean moving the `tour.addStep` code to be executed right before the step is actually transitioned to, but I don't think there would be a problem with that.  Thoughts?

**Comment by alexlafroscia** [comment]
If you want to do it as multiple PRs that's OK too, I don't really care how that's handled.

**Comment by rwwagner90** [comment]
I'm not very good with git, sorry about that. I checked out this PR, but not sure what to do after that, as any sort of publishing or pushing happen in the main repo, instead of your fork.

As for elements that are not visible, that's what I implemented beforeShowPromise for. https://github.com/HubSpot/shepherd/pull/57

This allows you to do whatever Ember stuff you need to do to get your elements visible, and then resolve the promise, and it'll do the attachTo stuff.

Not sure I'm explaining myself the best here, but does that make sense?

**Comment by alexlafroscia** [comment]
Yeah, I think it does.  I'll mess with `beforeShowPromise` and see if I can get what I need out of that.

***

In terms of the Git stuff, I would
1) Check out the PR
2) Make a new branch off of mine
3) Push your new branch to your remote
4) Submit a PR from your new branch against my `remove-shepherd-component` branch

That way, we can look at just the changes that you make to this code, and when I close that PR it will add your code to this PR.  It's a little complicated, but does keep everything nice and organized.

**Comment by alexlafroscia** [comment]
Unfortunately, the `beforeShowPromise` doesn't help in this case; maybe I need to change the way that I'm doing the jQuery lookup.  Regardless of when the `beforeShowPromise` resolves, the tour service is attempting to look the element up right away, causing the element it finds to be `undefined`.

**Comment by rwwagner90** [comment]
`beforeShowPromise` works for normal attachTo because attachTo is evaluated in the show function. You'll have to change the jQuery lookup to essentially happen at the same time as Shepherd does their attachTo stuff. What do you need jQuery selectors for that could not be done with Shepherd's attachTo normally?

**Comment by alexlafroscia** [comment]
Pseudoselectors, IE `:first`, `:eq(0)`, etc

**Comment by rwwagner90** [comment]
Yeah, but is there not a way you can just add classes or ids or something to where you don't need those?

Also, as for this git PR stuff, I think the issue here is that your branch is in your forked repo. If you made a branch in the main repo, and then did a PR, I would be able to update that, I believe. I'm really not sure what to do to update it now.

**Comment by alexlafroscia** [comment]
For sure that's dynamically generated, like a list of items, where you want to bind to just the second or third one, it's really hard to add a specific class to just that one item to bind to.  Hence, pseudoselectors.  Maybe we should just pull that part out, but it seems like something that Shepherd should be able to support.

**Comment by rwwagner90** [comment]
Yeah, I think that would be best to be supported in Shepherd, not here. We can work with them to get that built into their attachTo.

Keeping in mind I really don't understand git, could you create a new branch in the main repo, then push all of the changes from this branch into it, and work in the main repo instead of your fork? That way I can actually update the PR, and I don't have to add remotes or do any special git stuff.

**Comment by alexlafroscia** [comment]
Yeah, I'll do that.

**Comment by rwwagner90** [comment]
I just did a test push to the branch, and it doesn't appear to have been added here. Should it have been?

**Comment by alexlafroscia** [comment]
I thought it would, but apparently not.  I'll close this PR and re-open it with the new branch.

**Pull request closed without merging**
