### PR TITLE
Implemented custom scrollToHandler.

### PR DESCRIPTION
**Pull request by craigsketchley**
Haven't got a test for this. Had a bit of trouble testing the scroll position. Any thoughts on the best way to do this?

### CODE REVIEW

**Comment by rwwagner90** [comment]
@craigsketchley I think you should be able to check `scrollTop` to find the scroll position. What have you tried so far?

**Comment by rwwagner90** [comment]
@craigsketchley want me to give testing a go?

**Comment by craigsketchley** [comment]
Hey, yeah, happy for you to have a go. I think I'm close but I'm having trouble finding a way to set the viewport size for testing. Checking if the window has scrolled to the current step element requires that some of the page is out of view. Currently when running the tests the window height and document height are the same so no scrolling occurs :(

**Comment by craigsketchley** [comment]
Just pushed where I'm at so you can see my thought process.

**Comment by craigsketchley** [comment]
I did see that you can specify the [viewport size](http://phantomjs.org/api/webpage/property/viewport-size.html) in PhantomJS. Any idea if we can use that?

**Comment by rwwagner90** [comment]
@craigsketchley There is currently a bug that makes Phantom not work. I'll see if I can get it working with Chrome this weekend.

**Comment by rwwagner90** [comment]
@craigsketchley I think the problem here is `document` and `window` and such are not necessarily just the app, they include the qunit container page, and the real container is `#ember-testing-container`. I just changed the tests to check that scroll is initially `0` and then `> 0` after the scrollTo, which means scrolling worked. Are you good with that test? I committed it to your PR branch.

**Comment by craigsketchley** [comment]
Yeah nice work. That makes sense. Your commit looks good to me.

**Comment by rwwagner90** [comment]
@craigsketchley got it all merged in, published version 2.0.5. Is there anything we need to document in README.md?

**Comment by craigsketchley** [comment]
@rwwagner90 I don't think we need to document anything. Just a fix.

**Pull request merged**
